### ISSUE TITLE
PF2E Quick rolls support

### ISSUE THREAD

**Issue by PupperooX** [espositos/fvtt-tokenactionhud#134]
Hey,
I wasn't sure how to contact re supporting PF2E quick rolls, but it's become the go to for most PF2E games so it'd be super handy to have the support added for that instead of Core roller.

Thanks for the hard work!

**Comment by espositos** [comment]
I will look into it, but I think PF2E Quick Rolls patches into the core rolls, so I shouldn't need to do anything to support it.

**Comment by espositos** [comment]
I am going to close this because I am almost certain they already work together. PF2E Quick Rolls doesn't/shouldn't need any special modification to support it. If you can provide evidence of a specific place where it's not doing what you expect, however, let me know and I'll be happy to take another look.
