### ISSUE TITLE
Suggestion - Revise the Item-Macro behaviour

### ISSUE THREAD

**Issue by Deuterazamus** [espositos/fvtt-tokenactionhud#169]
In DnD5e there is a popular workflow where you use Midi-QoL to execute an item and apply effects via DAE. In DAE there is an option to use ItemMacro to further customize the behavior of an item. This workflow is also the one chosen by the module DAE-SRD so many of the spells/items released there contain an itemMacro meant to be called by Midi-QoL/DAE, with parameters defined by those modules.

If TokenActionHud and ItemMacro are both installed TAH tries to call the macros without passing necessary parameters and spell/item execution obviously always fails.

TAH already has a setting to modify this behaviour, restoring the original item call:
![image](https://user-images.githubusercontent.com/68236513/107159721-2ca3b500-6992-11eb-82cb-6374d95a220f.png)
However the result isn't optimal as players see 2 buttons for the same spell/item and the (M) one is still useless, leading to frequent confusion:
![image](https://user-images.githubusercontent.com/68236513/107159781-79878b80-6992-11eb-82d0-93b09aba45bd.png)

What I'm asking is to revise the behaviour of TAH when ItemMacro is present, possibly modifying the existing setting, so that there is only one button and is the one calling the original item, without having the (M) one cluttering the HUD.

Thanks!

**Comment by espositos** [comment]
I've added choices to toggle between the three settings. Sorry it took a while. I'd appreciate your feedback!

**Comment by Deuterazamus** [comment]
Installed, configured and tested - works beautifully. My players thank you

**Comment by grendel111111** [comment]
I know this is sorted for 5e, but is it possible to add an option to just have the one button that fires both at the same time as an option? So I have a spell (power in SWADE) that will do an attack, I have the item macro that does a visual effect of a lighting bolt. Because I can't use DAE or Midi QOL I can't set them up like 5e to trigger of each other.  An option to have a single button that both runs the macro and the basic function of the weapon item at the same time would be great (But I don't know if possible). It would then mean it would to the visual effect and send the attack to SWADE tools with one button.
