### ISSUE TITLE
Hover menu not disappearing

### ISSUE THREAD

**Issue by Shadoghast** [espositos/fvtt-tokenactionhud#4]
After right-clicking on the token to bring up the action hud, clicking anywhere else does not cause the action hud to disappear, although the core player hud dissapears.

**Comment by espositos** [comment]
For the moment I cannot reliably track the presence of the core player HUD, so I can't connect the appearance of my HUD to the core player HUD. I also haven't worked out how to connect it to token hovering, because you stop hovering over the token to interact with the action HUD. But I will try to think of a way to improve this.

**Comment by espositos** [comment]
Sorry, I will probably not get around to improving this so I am closing the issue for the moment. Pull requests are welcome, though.
