### ISSUE TITLE
Obsidian Character Sheets Support

### ISSUE THREAD

**Issue by NukeMaster0** [espositos/fvtt-tokenactionhud#60]
I was wonder if there would ever be a support format for this module, as it does not update after using ammo and such.

**Comment by espositos** [comment]
I don't know anything about Obsidian Character sheets, but I will ask Fyorl. I am hesitant to do this because it would make the HUD a bit dependent on Obsidian updates. I will look into it.

**Comment by espositos** [comment]
Hey Nukemaster, I looked into this, but due to the changes Obsidian Character sheets makes to the actor object and my lack of knowledge in its inner workings, I think I will not have time for this. Sorry about that, but I will revisit it at a later date and see where things stand. It might be easier to do then.

**Comment by espositos** [comment]
I'll leave it open as a reminder.

**Comment by espositos** [comment]
Sorry, I am closing this, I don't think I will ever get around to it as I have no time at the moment. I am open to pull requests for anyone else who wishes to implement it.

**Comment by espositos** [comment]
Added in 0.10.20 thanks to Avelyne0.
