### ISSUE TITLE
Token HUD not appearing

### ISSUE THREAD

**Issue by SilentAnnex** [espositos/fvtt-tokenactionhud#70]
Foundry - 0.6.6
DnD5e - 0.96

Module was confirmed working two weeks ago last session. Preparing for session today and noticed that bars were absent after updating. 

Module appears in module list as installed and updated.
![image](https://user-images.githubusercontent.com/71075937/92724616-dab71e80-f362-11ea-83e5-aa68139299e9.png)

Module also appears under Manage Modules.
![image](https://user-images.githubusercontent.com/71075937/92724796-181bac00-f363-11ea-9371-d229f92cb65d.png)

Module does not appear within Game Settings -> Module Settings. So no configuration present. 

Full module list can be provided if required.

**Comment by SilentAnnex** [comment]
Worth mentioning that I've also created a new blank game with Token Hud being the only active module. Still no success. 
![image](https://user-images.githubusercontent.com/71075937/92725361-f2db6d80-f363-11ea-90d4-518ae2ef9b92.png)
![image](https://user-images.githubusercontent.com/71075937/92725334-e8b96f00-f363-11ea-863d-28eb4c0bdf32.png)

**Comment by espositos** [comment]
Sorry about this, a few people have now reported this issue but I'm having trouble diagnosing it. I think the issue is linked to a change I made to the module.json, so I have made an update which may help but I don't know. I'll continue investigating. If you can check your console for any errors in the game with only the HUD installed, that would be useful to see.

**Comment by espositos** [comment]
So I think this is resolved. It would be great to know if it working for you now.

**Comment by espositos** [comment]
Assuming this is resolved.
